#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t ev"

$L "Welcome to Android `getprop ro.build.version.release` / `getprop ro.build.romversion`";
$L "Attempting to boot Evervolv AOSP ICS ROM.";
$L "Please visit www.evervolv.com for updates.";
$L "Also follow @preludedrew on twitter for latest n greatest.";
$L "__________                               ______       ";
$L "___  ____/__   ________________   __________  /__   __";
$L "__  __/  __ | / /  _ \_  ___/_ | / /  __ \_  /__ | / /";
$L "_  /___  __ |/ //  __/  /   __ |/ // /_/ /  / __ |/ / ";
$L "/_____/  _____/ \___//_/    _____/ \____//_/  _____/  ";
$L "                                                      ";
