#!/system/bin/sh
#
# handle swap filesystems
#
# Andrew Sutherland - (2013.07.21)

BB=/system/xbin/busybox
logI="log -p i -t handleswap"
logE="log -p e -t handleswap"

if [ ! -e /proc/swaps ]; then exit; fi

# find SD Card
for MMC_NUM in $(seq 0 9); do
    if [ ! -e /sys/block/mmcblk${MMC_NUM}/device/type ]; then continue; fi
    MMC_TYPE=$($BB cat /sys/block/mmcblk${MMC_NUM}/device/type)
    if [ "$MMC_TYPE" = "SD" ]; then
        SWAP_PART=$($BB fdisk -l /dev/block/mmcblk${MMC_NUM} | $BB awk '/^\// && $5 == 82 {print $1;exit;}')
        break
    fi
done

# enable swap
if [ -n "$SWAP_PART" ]; then
    if [ -b $SWAP_PART ]; then
        $BB swapon $SWAP_PART >/dev/null
        [ $? -ne 0 ] && $logE "Error: swapon returned $?"
        swapsize=$($BB fdisk -l $SWAP_PART | $BB awk '/^Disk/ {print $3;exit;}')
        $logI "Initialized ${swapsize}MB of swap on $SWAP_PART"
    else
        $logE "Error: $SWAP_PART not found"
    fi
fi
